### ISSUE TITLE
Order the Cards

### ISSUE THREAD

**Issue by joshualang** [joshualang/capstone-project#2]
## Value statement - a requirement, not a solution
As a **User** 
I need **My vaccintions ordered** 
so that **I can get a quick overview** 
## Description (Text, Scribble, Wireframe, Design)
All entries should get sorted by the following principle:
- Due Boosters on top
- Done Boosters
- Basic Immunization on bottom 
over each category should be a matching headline
## Acceptance criteria
- [ ] Cards are always and automatically organized in the three categories Basic Immunization, Boosters and Due
- [ ] Crads in one Category should be ordered by date decending 
- [ ] (functional descriptions)
- [ ] A11y
- [ ] Organized Codebase
- [ ] Well Documented Components
## Tasks
- [ ] create a function that gets the normalized data and orders it, so it gets rendered correctly
## Size
small
