### ISSUE TITLE
Add new Vaccination

### ISSUE THREAD

**Issue by joshualang** [joshualang/capstone-project#3]
## Value statement - a requirement, not a solution
As a **User** 
I need **Something to add my new Vaccinations** 
so that **They're documented** 
## Description (Text, Scribble, Wireframe, Design)
A new page where you can fill in all the necessary information about your new vaccination 
## Acceptance criteria
- [ ] The page is reachable from the overview
- [ ] Input for the date
- [ ] Input for the sticker
- [ ] Input for the disease
- [ ] Input for the doctor
- [ ] Focus on first field at start and after submit
- [ ] Submit button disabled until all fields are valid
- [ ] Success message after save
- [ ] Back arrow at the top navigation
- [ ] A11y
- [ ] Organized Codebase
- [ ] Well Documented Components
## Tasks
- [ ] create new page with routing
- [ ] create all components
- [ ] add the necessary logic to the inputs
- [ ] create a new cards object and save it
## Size
medium
