### ISSUE TITLE
Save Data locally

### ISSUE THREAD

**Issue by joshualang** [joshualang/capstone-project#4]
## Value statement - a requirement, not a solution
As a **User** 
I need **to keep my data through sessions** 
so that **they are saved for the future** 
## Description (Text, Scribble, Wireframe, Design)
- no visible impact
## Acceptance criteria
- [ ] on start load from local storage
- [ ] every change on cards should trigger a save to local storage
- [ ] A11y
- [ ] Organized Codebase
- [ ] Well Documented Components
## Tasks
- [ ] create services.js
- [ ] implement save and read
## Size
small
