### ISSUE TITLE
Open card to get further information

### ISSUE THREAD

**Issue by joshualang** [joshualang/capstone-project#8]
## Value statement - a requirement, not a solution
As a **User** 
I need **To get all information stored in one card** 
so that **I have acces to every detail** 
## Description (Text, Scribble, Wireframe, Design)
When card is clicked it should expand and push all other cards off screen.
A card should hold the information of:
- disease type
- date
- doctor
- sticker
## Acceptance criteria
- [ ] every card is clickable
- [ ] animated expansion
- [ ] specific data to card is shown
- [ ] styling equals design
- [ ] A11y
- [ ] Organized Codebase
- [ ] Well Documented Components
## Tasks
- [ ] implement react spring
- [ ] resize component on click
- [ ] swap out children
## Size
medium
